=== walkingtyphoon/Java_Project/out/production/Java workspace/alibaba/inclass/demo4/Test01/t.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://www.test.com"
           xmlns:tn="http://www.test.com">

    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="price" type="xs:decimal"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="bookUnique">
            <xs:selector xpath="tn:book"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== walkingtyphoon/Java_Project/src/alibaba/inclass/demo4/Test01/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<tn:books xsi:schemaLocation="http://www.test.com t.xsd" xmlns:tn="http://www.test.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tn:book id="1">
        <tn:title>a</tn:title>
        <tn:price>10</tn:price>
    </tn:book>
    <tn:book id="2">
        <tn:title>a</tn:title>
        <tn:price>10</tn:price>
    </tn:book>
    <tn:book id="3">
        <tn:title>a</tn:title>
        <tn:price>10</tn:price>
    </tn:book>
</tn:books>
