=== walkingtyphoon/Java_Project/out/production/Java workspace/alibaba/inclass/demo4/dtd/user.dtd
<?xml version = '1.0' encoding="UTF-8"?>
        <!ELEMENT users (user+)>
        <!ELEMENT user (name,age,gender,salary) >
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT gender (#PCDATA) >
        <!ELEMENT salary (#PCDATA) >
        <!ATTLIST user id ID >
        <!--
        <?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT students (student+) >
        <!ELEMENT student (name,age,sex)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT sex (#PCDATA)>
        <!ATTLIST student number ID #REQUIRED>-->

=== walkingtyphoon/Java_Project/src/alibaba/inclass/demo4/dtd/01.xml
<?xml version='1.0' encoding="UTF-8" ?>
<!DOCTYPE users SYSTEM "D:\File_System\Personal_Affairs\Java workspace\src\alibaba\inclass\Demo4\dtd\user.dtd">
<users>

    <user id="1">
        <name>张三</name>
        <age>34</age>
        <gender>男</gender>
        <salary>3000</salary>
    </user>
    <user id="2">
        <name>李四</name>
        <age>21</age>
        <gender>女</gender>
        <salary>4000</salary>
    </user>
    <user id="3">
        <name>王五</name>
        <age>46</age>
        <gender>女</gender>
        <salary>6500</salary>
    </user>
    <user id="4">
        <name>赵六</name>
        <age>28</age>
        <gender>男</gender>
        <salary>4400</salary>
    </user>
    <user id="5">
        <name>钱七</name>
        <age>53</age>
        <gender>男</gender>
        <salary>12000</salary>
    </user>
</users>
