=== walkingtyphoon/Java_Project/src/alibaba/inclass/demo4/xsd/user.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 这是文档声明 -->

<xsd:schema xmlns="http://www.itcast.cn/xml"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.itcast.cn/xml"
            elementFormDefault="qualified">
    <!--  规范必须要有的  -->
    <xsd:element name="users">

        <!--  声明用户类型  -->
        <xsd:complexType>

            <xsd:sequence>
                <!--    设置ID的属性信息     -->
                <xsd:element name="user" maxOccurs="unbounded">

                    <xsd:complexType>
                        <!--设置用户类型-->
                        <xsd:sequence>
                            <xsd:element name ="name" type="nameType" />
                            <!--设置用户的年龄-->
                            <xsd:element name = "age" type="ageType" />
                            <!--设置用户的性别-->
                            <xsd:element name = "gender" type="genderType" />
                            <!--设置用户的工资-->
                            <xsd:element name = "salary" type="salaryType" />
                        </xsd:sequence>
                        <xsd:attribute name = "id" type="xsd:ID" />
                        <!--设置用户的id-->
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>


    <!--创建用户的姓名属性-->
    <xsd:simpleType name="nameType">
        <xsd:restriction base="xsd:string">
            <!--设置输入值类型-->
            <xsd:pattern value="\w{2,4}"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!--创建用户的年龄属性-->
    <xsd:simpleType name="ageType">
        <xsd:restriction base="xsd:integer">
            <!--设置输入值类型-->
            <xsd:minInclusive value="1"/>
            <xsd:maxInclusive value="100"/>
        </xsd:restriction>

    </xsd:simpleType>

    <!--设置性别属性-->
    <xsd:simpleType name="genderType">
        <xsd:restriction base="xsd:string">
            <!--设置字符串类型-->
            <xsd:enumeration value="male"/>
            <xsd:enumeration value="female"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!--设置工资属性-->
    <xsd:simpleType name="salaryType">
        <xsd:restriction base="xsd:integer">
            <!--设置工资类型-->
            <xsd:minInclusive value="0"/>
            <xsd:maxInclusive value="2147483647"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== walkingtyphoon/Java_Project/src/alibaba/inclass/demo4/xsd2/03.xml
<?xml version='1.0' encoding="UTF-8" ?>

<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.itcast.cn/xml"
       xsi:schemaLocation="http://www.itcast.cn/xml user.xsd">

    <user>
        <id>1</id>
        <name>张三</name>
        <age>34</age>
        <gender>female</gender>
        <salary>3000</salary>
    </user>
    <user>
        <id>2</id>
        <name>张三</name>
        <age>21</age>
        <gender>male</gender>
        <salary>4000</salary>
    </user>
    <user>
        <id>3</id>
        <name>王五</name>
        <age>46</age>
        <gender>male</gender>
        <salary>6500</salary>
    </user>
    <user>
        <id>4</id>
        <name>赵六</name>
        <age>28</age>
        <gender>female</gender>
        <salary>4400</salary>
    </user>
    <user>
        <id>5</id>
        <name>钱七</name>
        <age>15</age>
        <gender>male</gender>
        <salary>12000</salary>
    </user>
</users>
